name: Build and deploy backend to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: windows-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build-backend
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download backend
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: ./backend

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_110B0715DB3C4DCC9D9D44A240A17237 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_36E3FB2FA0C74185B8B11A21EB7B8092 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_68AA7AEEA8D34F99A2803857941089E3 }}

      - name: Deploy backend to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'webappgestionformacionesdev'
          slot-name: 'Production'
          package: ./backend